name: RamBiel
favicon: null
layout_spectrum: 0.7683181460015476
typography_spectrum: 0.5611170779448003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4037505271844566
  lightness: 0.8355943413916975
  saturation: 0.7855575832072645
  rhythmicContrast: 0.6425557981710881
purpose: []
